eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://user:password@localhost:1111}/eureka/
security:
  user:
    password: ${eureka.password}

---
spring:
  profiles: heroku
eureka:
  instance:
    hostname: ${DOMAIN_NAME:localhost}
    nonSecurePort: 80
  password: ${USER_PASSWORD:password}
 
# HTTP Server
